
# CONFIGURACIÓN DEL SERVIDOR

spring.application.name=crm-backend

server.port=8080


# CONFIGURACIÓN DE LA BASE DE DATOS

spring.datasource.url=jdbc:postgresql://localhost:5432/crm_db
spring.datasource.username=postgres
spring.datasource.password=Tokio17*



# CONFIGURACIÓN JPA / HIBERNATE

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect